psql_app_name: "{{ hapi_psql_app_name }}"
application_name: "{{ fhir_server_application_name }}"

postgresql_pv_capacity: 5Gi 
postgresql_version: 12-el8
postgresql_is_namespace: openshift
postgresql_service_account: "{{ psql_app_name }}"
psql_user_name: "{{ hapi_psql_user_name }}"
psql_user_passwd: "{{ hapi_psql_user_passwd }}"
psql_db_name: "{{ hapi_psql_db_name }}"
psql_credentials_secret: "{{ psql_app_name }}"
postgresql_max_prepared_transactions: 100
postgresql_max_connections: 100
postgresql_init_configmap: "{{ psql_app_name }}-init"
postgresql_memory_limit: 512Mi
postgresql_cpu_limit: 500m
postgresql_memory_request: 256Mi
postgresql_cpu_request: 100m
psql_init_scripts:
undeploy_fhir_db: "true"

service_account: "{{ application_name }}"
application_properties: application.yaml
application_configmap: "{{ application_name }}"
application_configmap_key: "{{ application_properties }}"
binary_imagestream_template: binary-imagestream.yml 

# https://github.com/redhat-naps-da/hapi-fhir-jpaserver-starter
service_image: quay.io/redhat_naps_da/hapi-fhir-jpaserver-starter-ocp
service_image_tag: v5.3.0-psql-bytea-1

application_template: fhir-server-service.yml
fhirserver_java_max_mem_ratio: 60
fhirserver_java_initial_mem_ratio: 0
fhirserver_gc_max_metaspace_size: 500

hapi_psql_debezium_conf_name: hapi-psql-debezium-conf
hapi_psql_debezium_conf_file: "{{ hapi_psql_debezium_conf_name }}.conf"

# Debezium configs
kafka_debezium_template: debezium-fhir-server-pgsql.yml
kafka_debezium_name: debezium-fhir-server-pgsql
kafka_debezium_tasks_max: 1

kafka_debezium_schema_whitelist: public
