---

- name: "get CSV for "
  kubernetes.core.k8s_info:
    kind: ClusterServiceVersion
    api_version: operators.coreos.com/v1alpha1
    namespace: "{{ subscription_namespace }}"
    label_selectors:
      - "operators.coreos.com/{{ subscription_name }}.{{ subscription_namespace }}"
  register: r_subscription
- debug:
    msg: "{{ r_subscription.resources[0].metadata.name }}"
  when: r_subscription.resources[0] is defined

- name: "remove clusterserviceversion for {{ operator_name }} operator"
  k8s:
    state: absent
    kind: ClusterServiceVersion
    api_version: operators.coreos.com/v1alpha1
    name: "{{ r_subscription.resources[0].metadata.name }}"
    namespace: "{{ subscription_namespace }}"
  when: 
  - r_subscription.resources[0] is defined

- name: "remove subscription for {{ operator_name }} operator"
  k8s:
    state: absent
    kind: Subscription
    api_version: operators.coreos.com/v1alpha1
    name: "{{ subscription_name }}"
    namespace: "{{ subscription_namespace }}"
