---

- name: delete nexus deployment
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ nexus_service_name }}"
    namespace: "{{ namespace }}"
    kind: deploymentconfig

- name: delete nexus route
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ nexus_service_name }}"
    namespace: "{{ namespace }}"
    kind: route

- name: delete nexus service
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ nexus_service_name }}"
    namespace: "{{ namespace }}"
    kind: service

- name: delete nexus pvc
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ nexus_service_name }}-pv"
    namespace: "{{ namespace }}"
    kind: pvc

- name: delete nexus imagestream
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: absent
    name: "{{ nexus_service_name }}"
    namespace: "{{ namespace }}"
    kind: imagestream
