psql_app_name: "{{ rhpam_psql_app_name }}"
application_name: "{{ sepsisdetection_rhpam_app_name }}"

postgresql_pv_capacity: 5Gi 
postgresql_version: 12-el8
postgresql_is_namespace: openshift
postgresql_service_account: "{{ psql_app_name }}"
psql_user_name: "{{ rhpam_psql_user_name }}"
psql_user_passwd: "{{ rhpam_psql_passwd }}"
psql_db_name: "{{ rhpam_psql_db_name }}"
psql_credentials_secret: "{{ psql_app_name }}"
postgresql_max_prepared_transactions: 100
postgresql_max_connections: 100
postgresql_init_configmap: "{{ psql_app_name }}-init"
postgresql_memory_limit: 512Mi
postgresql_cpu_limit: 500m
postgresql_memory_request: 256Mi
postgresql_cpu_request: 100m
undeploy_psql_bpm: "false"

quartz_clustered: false

service_account: "{{ application_name }}"
application_properties: application.properties
application_configmap: "{{ application_name }}"
application_configmap_key: "{{ application_properties }}"
binary_imagestream_template: binary-imagestream.yml 
service_image: quay.io/redhat_naps_da/sepsisdetection-rhpam
service_image_tag: 0.0.12
application_template: sepsisdetection-rhpam.yml
sepsisdetection_rhpam_java_max_mem_ratio: 60
sepsisdetection_rhpam_java_initial_mem_ratio: 0
sepsisdetection_rhpam_gc_max_metaspace_size: 500

# Location on image file system where sepsisdetection-rhpam.xml  (which defines deployed KIE containers) will reside
kie_server_repo_path: /deployments/config
kie_admin_user: admin
kie_admin_password: user
kieserver_user_password: "{{ sepsisdetection_rhpam_api_passwd }}"

kie_deployment_name: "{{ sepsisdetection_rhpam_deployment_name }}"
kie_deployment_version: "{{ sepsisdetection_rhpam_deployment_version }}"
kie_process_id: "{{ sepsisdetection_rhpam_process_id }}"
fhir_server_url: "http://{{ fhir_server_application_name }}:8080"
