---

- name: Deploy Nexus 2
  hosts: localhost
  connection: local
  gather_facts: false
  run_once: true
  vars_files:
    - group_vars/tools.yml

  tasks:
    - set_fact:
        namespace: "{{ namespace_nexus }}"
        resources_dir: "{{ resources_base_dir }}/nexus"
        work_dir_name: nexus
    - include_role:
        name: ../roles/nexus
      when: >
        ACTION is not defined or
        ACTION is none or
        ACTION|trim() == "" or
        ACTION|trim() == "install"
    - include_role:
        name: ../roles/nexus
        tasks_from: uninstall
      when: >
        ACTION is defined and
        ACTION|trim() == "uninstall"
