---

home_dir: "{{ playbook_dir }}/.."

# resources dir
resources_base_dir: "{{ home_dir }}/resources"

# oc executable
openshift_cli: oc

# The OCP user that will own all resources in the generated OCP namespace
project_admin: user1

# Name of the OCP project to deploy this application to
project_name: "{{ project_admin }}-sepsisdetection"




# Namespace where SSO will be installed
namespace_sso: sepsisdetection-sso

sso_siteadmin_password: r3dh4t1!

# If set to True, then every user that creates an account in demo will automatically be a "realm-admin"
set_realm_admin_as_default: false

sso_realm_id: "{{ project_admin }}-sepsis"

sso_clientId: sepsisdetection


# The following two options are allowed:
#   image  : Use if a container image of your application is already available from a public container image repo:  ie:  quay.io , registry.redhat.io or docker hub
#   source : Use if this ansible includes tasks to deploy a Jenkins or Tekton BuildConfig that creates the application image from source code
deploy_from: image

kafka_debezium_db_server_name: fhir
kafka_debezium_table_whitelist: public.hfj_res_ver

# Topic that Debezium will stream to and triggers BPM process
kafka_debezium_topic: "{{ kafka_debezium_db_server_name }}.{{ kafka_debezium_table_whitelist }}"


fhir_server_application_name: fhir-server
sepsisdetection_rhpam_app_name: sepsisdetection-rhpam
sepsisdetection_rhpam_api_passwd: kieserver
sepsisdetection_rhpam_deployment_name: sepsisdetection-kjar
sepsisdetection_rhpam_deployment_version: 1.0.0
sepsisdetection_rhpam_process_id: sepsisdetection

namespace_knativeserving: knative-serving
namespace_knativeeventing: knative-eventing


sepsis_detection_ml_app_name: sepsis-detection

sepsisdetection_ui_app_name: sepsisdetection-ui

patient_viewer_url: "https://healthflow-dev-fe.herokuapp.com/profile/5e3ad7fe-24fa-4dc2-8be5-25554a8efb2c"

sepsisdetection_sse_app_name: sepsisdetection-sse
