---

- name: check if {{ application_name }} application is deployed
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: list
    namespace: "{{ namespace }}"
    name: "{{ application_name }}"
    kind: dc
  register: result

- name: "create service account {{ application_name }}"
  oc_serviceaccount:
    oc_binary: "{{ openshift_cli }}"
    state: present
    name: "{{ application_name }}"
    namespace: "{{ namespace }}"

- name: copy imagestream template
  template:
    src: "{{ resources_dir }}/{{ binary_imagestream_template }}"
    dest: "{{ work_dir }}/{{ binary_imagestream_template }}"

- name: create imagestream {{ application_name }} in the {{ namespace }} project
  oc_obj:
    oc_binary: "{{ openshift_cli }}"
    state: present
    namespace: "{{ namespace }}"
    kind: imagestream
    name: "{{ application_name }}"
    files:
      - "{{ work_dir }}/{{ binary_imagestream_template }}"

- name: retrieve sso route
  shell: "{{ openshift_cli }} get route sso -o jsonpath='{.spec.host}' -n {{ namespace_sso }}"
  register: sso_route_cmd

- name: set env var facts
  set_fact:
    sepsisdetection_rhpam_hostname: "{{ sepsisdetection_rhpam_app_name }}-{{ project_name }}.{{ ocp_domain }}"
    fhir_server_application_hostname: "{{ fhir_server_application_name }}-{{ project_name }}.{{ ocp_domain }}"
    sso_url: "https://{{ sso_route_cmd.stdout }}"

- name: copy env.js file to work directory
  template:
    src: "{{ resources_dir }}/env.js"
    dest: "{{ work_dir }}/env.js"

- name: create {{ application_name }} configmap
  oc_configmap:
    oc_binary: "{{ openshift_cli }}"
    state: present
    name: "{{ application_name }}"
    namespace: "{{ namespace }}"
    from_file:
      dir: "{{ work_dir }}/env.js"

- name: copy application template
  template:
    src: "{{ resources_dir }}/{{ application_template }}"
    dest: "{{ work_dir }}/{{ application_template }}"


- name: deploy {{ application_name }} application
  oc_list:
    oc_binary: "{{ openshift_cli }}"
    state: present
    namespace: "{{ namespace }}"
    files:
      - "{{ work_dir }}/{{ application_template }}"
  when: result.ansible_module_results.stderr is defined and result.ansible_module_results.stderr != ""

- name: "wait until {{ application_name }} application is up and running"
  shell: "{{ openshift_cli }} get dc {{ application_name }} -o template --template={{ json_template }} -n {{ namespace }}"
  vars:
    json_template: '\{\{.status.readyReplicas\}\}'
  register: result
  until: result.stdout == "1"
  retries: 10
  delay: 30
  changed_when: false
